"""Phase2前置：status枚举更新+新增字段

Revision ID: 42097bdbd61a
Revises: 252a79df66dd
Create Date: 2026-05-15 16:33:16.586924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42097bdbd61a'
down_revision: Union[str, Sequence[str], None] = '252a79df66dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先迁移旧数据：重命名的状态值需先 UPDATE，否则 ALTER ENUM 会失败
    op.execute("UPDATE documents SET status='uploaded' WHERE status='uploading'")
    op.execute("UPDATE documents SET status='vector_storing' WHERE status='indexing'")
    # 修改 documents.status ENUM：重命名 + 新增值
    op.execute(
        "ALTER TABLE documents MODIFY COLUMN status "
        "ENUM('uploaded','parsing','chunking','embedding','vector_storing',"
        "'completed','success_with_warnings','partial_failed','failed','deleting') "
        "NOT NULL DEFAULT 'uploaded'"
    )
    op.add_column('documents', sa.Column('file_path', sa.String(length=512), nullable=True, comment='文件存储路径：uploads/{kb_id}/{doc_id}/{uuid}_{sanitized_filename}'))
    op.add_column('documents', sa.Column('current_stage', sa.String(length=32), nullable=True, comment='当前处理阶段，用于断点恢复'))
    op.add_column('documents', sa.Column('last_success_batch', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='最后成功的批次号，用于批次级 checkpoint'))
    op.create_index('idx_kb_filename', 'documents', ['kb_id', 'filename'], unique=False)
    op.add_column('knowledge_bases', sa.Column('status', sa.Enum('active', 'deleting', name='kb_status'), nullable=False, server_default=sa.text("'active'"), comment='active（正常）/ deleting（异步清理中，随后物理删除行）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'status')
    op.drop_index('idx_kb_filename', table_name='documents')
    op.drop_column('documents', 'last_success_batch')
    op.drop_column('documents', 'current_stage')
    op.drop_column('documents', 'file_path')
    # 还原 documents.status ENUM
    op.execute("UPDATE documents SET status='uploading' WHERE status='uploaded'")
    op.execute("UPDATE documents SET status='indexing' WHERE status='vector_storing'")
    op.execute(
        "ALTER TABLE documents MODIFY COLUMN status "
        "ENUM('uploading','parsing','chunking','embedding','indexing',"
        "'completed','failed') "
        "NOT NULL DEFAULT 'uploading'"
    )
    # ### end Alembic commands ###
