"""knowledge_bases新增visibility字段

Revision ID: 8fa3ea12b75e
Revises: 687b64790b37
Create Date: 2026-05-24 20:22:37.394668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fa3ea12b75e'
down_revision: Union[str, Sequence[str], None] = '687b64790b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_bases', sa.Column('visibility', sa.Enum('private', 'public', name='kb_visibility'), server_default=sa.text("'private'"), nullable=False, comment='private（仅owner可见）/ public（所有用户可检索）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'visibility')
    # ### end Alembic commands ###
